name: PR Fast

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - dev
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-macos-arm64:
    name: Compile
    uses: ./.github/workflows/build-macos-arm64.yml
    with:
      chain-network: ${{ github.ref_name == 'main' && 'mainnet' || 'testnet' }}
      release: false
  build-macos-intel:
    name: Compile
    uses: ./.github/workflows/build-macos-intel.yml
    with:
      chain-network: ${{ github.ref_name == 'main' && 'mainnet' || 'testnet' }}
      release: false

  build-linux:
    name: Compile
    uses: ./.github/workflows/build-linux.yml
    with:
      chain-network: ${{ github.ref_name == 'main' && 'mainnet' || 'testnet' }}
      release: false

  build-windows:
    name: Compile
    uses: ./.github/workflows/build-windows.yml
    with:
      chain-network: ${{ github.ref_name == 'main' && 'mainnet' || 'testnet' }}