name: PR

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request_review:
  pull_request:
    types:
      - review_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: Compile
#    if: github.event.review.state == 'approved' && !github.event.pull_request.draft
    uses: ./.github/workflows/build-linux.yml
    with:
      chain-network: ${{ github.ref_name == 'main' && 'mainnet' || 'testnet' }}

  build-windows:
    name: Compile
#    if: github.event.review.state == 'approved' && !github.event.pull_request.draft
    uses: ./.github/workflows/build-windows.yml
    with:
      chain-network: ${{ github.ref_name == 'main' && 'mainnet' || 'testnet' }}

  build-macos-arm64:
    name: Compile
    uses: ./.github/workflows/build-macos-arm64.yml
    with:
      chain-network: ${{ github.ref_name == 'main' && 'mainnet' || 'testnet' }}

  build-macos-intel:
    name: Compile
#    if: github.event.review.state == 'approved' && !github.event.pull_request.draft
    uses: ./.github/workflows/build-macos-intel.yml
    with:
      chain-network: ${{ github.ref_name == 'main' && 'mainnet' || 'testnet' }}

