name: build-macos-intel

on:
  workflow_call:
    inputs:
      chain-network:
        description: "The network to use, can either be testnet, stagenet or mainnet"
        default: testnet
        required: false
        type: string
      build-cli:
        description: "Should the CLI be built"
        default: true
        required: false
        type: boolean
      release:
        description: "Make a release"
        default: true
        required: false
        type: boolean

jobs:
  build:
    name: MacOS Intel
    runs-on: macos-13
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install miniupnpc boost openssl@3

      - name: Build CLI
        if: ${{ inputs.build-cli }}
        uses: ./.github/actions/cmake-build
        with:
          jobs: '4'
          build-type: 'Release'
          chain-network: ${{ inputs.chain-network }}
          boost-root: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          target: 'daemon simplewallet'
          arch: 'x86'
          system-deps: true

      - name: CLI Artifacts
        if: ${{ inputs.build-cli }}
        uses: ./.github/actions/sign-and-upload-release
        with:
          chain-network: ${{ inputs.chain-network }}
          release-tag: ${{ github.ref_name }}
          release: "${{ inputs.release }}"
          assets: |
            zanod
            simplewallet
          asset-type: 'cli'
          asset-directory: ${{ github.workspace }}/build/release-static/src
