name: build-macos-arm64
permissions:
  contents: write
on:
  workflow_call:
    inputs:
      chain-network:
        description: "The network to use, can either be testnet, stagenet or mainnet"
        default: testnet
        required: false
        type: string
      build-cli:
        description: "Should the CLI be built"
        default: true
        required: false
        type: boolean
      release:
        description: "Make a release"
        default: true
        required: false
        type: boolean
      release-tag:
        required: false
        type: string
        description: 'The tag for the release'

jobs:
  build-cli:
    name: MacOS Arm64
    runs-on: macos-14
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install miniupnpc pkg-config openssl@3 boost

      - name: Build CLI
        uses: ./.github/actions/cmake-build
        with:
          jobs: '3'
          build-type: 'Release'
          chain-network: ${{ inputs.chain-network }}
          target: 'daemon simplewallet'
          arch: 'aarch64'
          system-deps: true


      - name: CLI Artifacts
        if: ${{ inputs.build-cli }}
        uses: ./.github/actions/sign-and-upload-release
        with:
          chain-network: ${{ inputs.chain-network }}
          release-tag: ${{ github.ref_name }}
          release: "${{ inputs.release }}"
          assets: |
            zanod
            simplewallet
          asset-type: 'cli'
          asset-directory: ${{ github.workspace }}/build/release-static/src
