name: build-windows

on:
  workflow_call:
    inputs:
      chain-network:
        description: "The network to use, can either be testnet, stagenet or mainnet"
        default: testnet
        required: false
        type: string
      build-cli:
        description: "Should the CLI be built"
        default: true
        required: false
        type: boolean
      release:
        description: "Make a release"
        default: true
        required: false
        type: boolean

jobs:
  build:
    name: Windows
    runs-on: windows-2022
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14
      - uses: ilammy/setup-nasm@v1
      - name: Install Perl CPAN modules
        shell: powershell
        run: |
          choco install -y boost-msvc-14.3
          choco install -y openssl

      - name: Build CLI
        if: ${{ inputs.build-cli }}
        uses: ./.github/actions/cmake-build
        with:
          jobs: '4'
          build-type: 'Release'
          chain-network: ${{ inputs.chain-network }}
          target: 'daemon simplewallet'
          static: 'true'
          generator: 'Visual Studio 17 2022'
          arch: 'x86-64'
          system-deps: true


      - name: CLI Artifacts
        if: ${{ inputs.build-cli }}
        uses: ./.github/actions/sign-and-upload-release
        with:
          chain-network: ${{ inputs.chain-network }}
          release-tag: ${{ github.ref_name }}
          release: "${{ inputs.release }}"
          assets: |
            zanod.exe
            simplewallet.exe
          asset-type: 'cli'
          asset-directory: ${{ github.workspace }}\build\release\src\Release
