name: testnet-cli-windows

on:
  workflow_call:

jobs:
  build-project:
    name: Compile Windows CLI
    runs-on: windows-2022
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Eat the Choco
        run: |
          choco install ccache -y
          choco install zip -y

      - name: ccache caching
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/ccache
          key: ccache-testnet-cli-${{ runner.os }}

      - name: Install boost
        uses: MarkusJx/install-boost@6d8df42f57de83c5b326b5b83e7b35d650030103
        id: install-boost
        with:
          boost_version: 1.84.0
          boost_install_dir: ${{ github.workspace }}/build/boost_1_84_0
          platform_version: 2022
          toolset: msvc

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          CCACHE_TEMPDIR: ${{ github.workspace }}/build/ccache
        with:
          build-dir: build/release
          generator: Visual Studio 17 2022
          build-args: |
            -j4
            --config Release
          options: |
            STATIC=FALSE
            TESTNET=TRUE
            ARCH=x86-64
            CMAKE_BUILD_TYPE=Release
            Boost_INCLUDE_DIR=${{steps.install-boost.outputs.BOOST_ROOT}}/include
            Boost_LIBRARY_DIRS=${{steps.install-boost.outputs.BOOST_ROOT}}/lib

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: testnet-cli-windows
          path: |
            ${{ github.workspace }}/build/release/src/Release/zanod.exe
            ${{ github.workspace }}/build/release/src/Release/simplewallet.exe
            ${{ github.workspace }}/build/release/src/Release/connectivity_tool.exe
            ${{ github.workspace }}/build/release/src/zanod.exe
            ${{ github.workspace }}/build/release/src/simplewallet.exe
            ${{ github.workspace }}/build/release/src/connectivity_tool.exe
